<?php
$itens = [
    ["cat" => "metadados_e_seo", "cat-label" => "Metadados e SEO", "item" => "multiple_page_titles", "label" => "Multiple (0%) Page Titles"],
    ["cat" => "metadados_e_seo", "cat-label" => "Metadados e SEO", "item" => "over_60_characters_page_titles", "label" => "Over 60 Characters - Truncated (0%) Page Titles"],
    ["cat" => "metadados_e_seo", "cat-label" => "Metadados e SEO", "item" => "missing_page_titles", "label" => "Missing (0%) Page Titles"],
    ["cat" => "metadados_e_seo", "cat-label" => "Metadados e SEO", "item" => "duplicate_page_titles", "label" => "Duplicate (0%) Page Titles"],
    ["cat" => "metadados_e_seo", "cat-label" => "Metadados e SEO", "item" => "missing_meta_descriptions", "label" => "Missing (0%) Meta Descriptions"],
    ["cat" => "metadados_e_seo", "cat-label" => "Metadados e SEO", "item" => "duplicate_meta_descriptions", "label" => "Duplicate (0%) Meta Descriptions"],
    ["cat" => "metadados_e_seo", "cat-label" => "Metadados e SEO", "item" => "over_155_characters_meta_descriptions", "label" => "Over 155 Characters - Truncated (0%) Meta Descriptions"],
    ["cat" => "metadados_e_seo", "cat-label" => "Metadados e SEO", "item" => "seo_100", "label" => "SEO 100 Home e MPI"],
    ["cat" => "metadados_e_seo", "cat-label" => "Metadados e SEO", "item" => "banners_links_mpi", "label" => "Banners - links para MPI Home"],
    ["cat" => "metadados_e_seo", "cat-label" => "Metadados e SEO", "item" => "produtos_em_destaque", "label" => "Produtos em destaque Home"],
    ["cat" => "metadados_e_seo", "cat-label" => "Metadados e SEO", "item" => "coluna_lateral", "label" => "Coluna Lateral Todas as páginas"],
    ["cat" => "performance", "cat-label" => "Performance", "item" => "performance_60_home_e_mpi", "label" => "Performance > 60 Home e MPI"],
    ["cat" => "performance", "cat-label" => "Performance", "item" => "accessibility_90_home_e_mpi", "label" => "Accessibility > 90 Home e MPI"],
    ["cat" => "performance", "cat-label" => "Performance", "item" => "best_practices_90_home_e_mpi", "label" => "Best Pratices > 90 Home e MPI"],
    ["cat" => "performance", "cat-label" => "Performance", "item" => "footer_lazy_load_todas_as_paginas", "label" => "Footer Lazy Load Todas as páginas"],
    ["cat" => "validacao_de_codigo", "cat-label" => "Validação de Código", "item" => "w3c_html_home_e_mpi", "label" => "W3C HTML Home e MPI"],
    ["cat" => "validacao_de_codigo", "cat-label" => "Validação de Código", "item" => "w3c_css_home_e_mpi", "label" => "W3C CSS Home e MPI"],
    ["cat" => "urls", "cat-label" => "URLs", "item" => "non_ascii_characters_0_url", "label" => "Non ASCII Characters (0%) URL"],
    ["cat" => "urls", "cat-label" => "URLs", "item" => "uppercase_0_url", "label" => "Uppercase (0%) URL"],
    ["cat" => "urls", "cat-label" => "URLs", "item" => "multiple_slashes_0", "label" => "Multiple Slashes (0%)"],
    ["cat" => "urls", "cat-label" => "URLs", "item" => "contains_space_0", "label" => "Contains Space (0%)"],
    ["cat" => "estrutura_semantica", "cat-label" => "Estrutura Semântica", "item" => "missing_0_h1", "label" => "Missing (0%) H1"],
    ["cat" => "estrutura_semantica", "cat-label" => "Estrutura Semântica", "item" => "duplicate_0_h1", "label" => "Duplicate (0%) H1"],
    ["cat" => "estrutura_semantica", "cat-label" => "Estrutura Semântica", "item" => "multiple_0_h1", "label" => "Multiple (0%) H1"],
    ["cat" => "estrutura_semantica", "cat-label" => "Estrutura Semântica", "item" => "missing_0_h2", "label" => "Missing (0%) H2"],
    ["cat" => "estrutura_semantica", "cat-label" => "Estrutura Semântica", "item" => "nome_da_empresa_segmento_h1_home", "label" => "Nome da empresa + segmento (H1) Home"],
    ["cat" => "estrutura_semantica", "cat-label" => "Estrutura Semântica", "item" => "favicon_todas_as_paginas", "label" => "Favicon Todas as páginas"],
    ["cat" => "estrutura_semantica", "cat-label" => "Estrutura Semântica", "item" => "font_awesome_todas_as_paginas", "label" => "Font Awesome Todas as páginas"],
    ["cat" => "estrutura_semantica", "cat-label" => "Estrutura Semântica", "item" => "url_coerente_h1_pagina_todas_as_paginas", "label" => "URL coerente ao H1 da página Todas as páginas"],
    ["cat" => "fluxo", "cat-label" => "Fluxo", "item" => "pull_request", "label" => "Pull request"],
    ["cat" => "imagens", "cat-label" => "Imagens", "item" => "instrucao_1over_200kb_0_images", "label" => "Instrução 1Over 200kb (0%) Images"],
    ["cat" => "imagens", "cat-label" => "Imagens", "item" => "over_500kb_banner_0_images", "label" => "Over 500kb Banner (0%) Images"],
    ["cat" => "conteudo", "cat-label" => "Conteúdo", "item" => "spelling_errors_lorem_ipsum_content", "label" => "Spelling Errors (Lorem Ipsum) Content"],
    ["cat" => "conteudo", "cat-label" => "Conteúdo", "item" => "grammar_errors_lorem_ipsum_content", "label" => "Grammar Errors (Lorem Ipsum) Content"],
    ["cat" => "conteudo", "cat-label" => "Conteúdo", "item" => "readability_very_difficult_0_content", "label" => "Readability very difficult (0%) Content"],
    ["cat" => "layout_e_usabilidade", "cat-label" => "Layout e Usabilidade", "item" => "botao_link_whatsapp_home", "label" => "Botão Link (WhatsApp) Home"],
    ["cat" => "layout_e_usabilidade", "cat-label" => "Layout e Usabilidade", "item" => "mobile_smartphone_375px_home_e_mpi", "label" => "Mobile - Smartphone (375px) Home e MPI"],
    ["cat" => "layout_e_usabilidade", "cat-label" => "Layout e Usabilidade", "item" => "mobile_tablet_768px_home_e_mpi", "label" => "Mobile - Tablet (768px) Home e MPI"],
    ["cat" => "layout_e_usabilidade", "cat-label" => "Layout e Usabilidade", "item" => "active_menu_topo_todas_as_paginas", "label" => "Active menu topo Todas as páginas"],
    ["cat" => "layout_e_usabilidade", "cat-label" => "Layout e Usabilidade", "item" => "botoes_links_clicaveis_todas_as_paginas", "label" => "Botões - links clicáveis Todas as páginas"],
    ["cat" => "layout_e_usabilidade", "cat-label" => "Layout e Usabilidade", "item" => "contraste_entre_elementos_todas_as_paginas", "label" => "Contraste entre elementos Todas as páginas"],
    ["cat" => "layout_e_usabilidade", "cat-label" => "Layout e Usabilidade", "item" => "breadcrumbs_todas_as_paginas", "label" => "Breadcrumbs Todas as páginas"],
    ["cat" => "layout_e_usabilidade", "cat-label" => "Layout e Usabilidade", "item" => "menu_footer_menu_header_todas_as_paginas", "label" => "Menu Footer = Menu Header Todas as páginas"],
    ["cat" => "layout_e_usabilidade", "cat-label" => "Layout e Usabilidade", "item" => "broken_image_or_components", "label" => "Broken Image or Components"],
    ["cat" => "layout_e_usabilidade", "cat-label" => "Layout e Usabilidade", "item" => "disproportionate_elements", "label" => "Disproportionate Elements"],
    ["cat" => "contato", "cat-label" => "Contato", "item" => "telefones", "label" => "Telefones"],
    ["cat" => "contato", "cat-label" => "Contato", "item" => "endereco", "label" => "Endereço"],
    ["cat" => "contato", "cat-label" => "Contato", "item" => "formatacao_de_endereco", "label" => "Formatação de endereço"],
    ["cat" => "formularios", "cat-label" => "Formulários", "item" => "botao_cta_formulario_home", "label" => "Botão CTA (formulário) Home"],
    ["cat" => "formularios", "cat-label" => "Formulários", "item" => "campos_do_formulario", "label" => "Campos do formulário"],
    ["cat" => "formularios", "cat-label" => "Formulários", "item" => "recaptcha_formulario", "label" => "Recaptcha formulário"],
    ["cat" => "resposta_do_servidor", "cat-label" => "Resposta do Sevidor", "item" => "success_200_response_codes", "label" => "Success (200) Response Codes"],
    ["cat" => "resposta_do_servidor", "cat-label" => "Resposta do Sevidor", "item" => "redirection_301_302_response_codes", "label" => "Redirection (301, 302)Response Codes"],
    ["cat" => "resposta_do_servidor", "cat-label" => "Resposta do Sevidor", "item" => "client_error_0_response_codes", "label" => "Client Error (0%) Response Codes"],
    ["cat" => "resposta_do_servidor", "cat-label" => "Resposta do Sevidor", "item" => "server_error_0_response_codes", "label" => "Server Error (0%) Response Codes"],
    ["cat" => "seguranca", "cat-label" => "Segurança", "item" => "https_urls_100", "label" => "HTTPS URL’s (100%)"],
    ["cat" => "seguranca", "cat-label" => "Segurança", "item" => "mixed_content_0", "label" => "Mixed Content (0%)"],
    ["cat" => "seguranca", "cat-label" => "Segurança", "item" => "links_externos_outlinks_target_blank_rel_nofollow", "label" => "Links Externos - Outlinks (target=”_blank” rel=”nofollow”)"],
    ["cat" => "seguranca", "cat-label" => "Segurança", "item" => "sem_self_redirect_quem_somos_home", "label" => "Sem Self redirect (Quem somos) Home"],
    ["cat" => "publicacao", "cat-label" => "Publicação", "item" => "mpis_cadastradas_no_spider", "label" => "MPIs Cadastradas no Spider"],
    ["cat" => "publicacao", "cat-label" => "Publicação", "item" => "configuracao_no_servidor_100", "label" => "Configuração no Servidor 100%"],
    ["cat" => "publicacao", "cat-label" => "Publicação", "item" => "apontamentos_dns_100", "label" => "Apontamentos DNS 100%"],
    ["cat" => "publicacao", "cat-label" => "Publicação", "item" => "sensedata_preenchido_100", "label" => "SenseData Preenchido 100%"],
    ["cat" => "publicacao", "cat-label" => "Publicação", "item" => "upload_sitemap_searchconsole", "label" => "Upload Sitemap Searchconsole"],
    ["cat" => "publicacao", "cat-label" => "Publicação", "item" => "redirects_funcionando", "label" => "Redirects Funcionando"],
    ["cat" => "publicacao", "cat-label" => "Publicação", "item" => "configuracao_metricas_analytics", "label" => "Configuração Metricas Analytics"],
    ["cat" => "publicacao", "cat-label" => "Publicação", "item" => "configuracao_recaptcha", "label" => "Configuração Recaptcha"],
    ["cat" => "publicacao", "cat-label" => "Publicação", "item" => "configuracao_htaccess", "label" => "Configuração htaccess"],
];
